"use client"
import React, { useState } from 'react';
import LoginModal from "../Login/page";

const FAQSection = () => {
  const [openFAQ, setOpenFAQ] = useState(2);
  const [showLoginModal, setShowLoginModal] = useState(false);

  const faqs = [
    {
      question: "What is a copy?",
      answer: "A copy refers to written content created for marketing purposes, such as advertisements, website content, email campaigns, and other promotional materials designed to persuade and engage your target audience."
    },
    {
      question: "Does Copymatic offer a free trial?",
      answer: "Yes, Copymatic offers a free trial that allows you to explore our AI-powered writing tools and generate content to see how our platform can help boost your writing productivity."
    },
    {
      question: "Can I use Copymatic to write long articles (1,000+ words)?",
      answer: "Absolutely! One of our tools is a long-form article writer which is specifically designed to generate unlimited content per article. It lets you generate the blog title, outline, introduction, long paragraphs, or complete your text in seconds."
    },
    {
      question: "Is the generated content original?",
      answer: "Yes, all content generated by Copymatic is original and unique. Our AI creates fresh content based on your inputs and requirements, ensuring that each piece is plagiarism-free and tailored to your specific needs."
    },
    {
      question: "How long would it take to write an article with AI?",
      answer: "With Copymatic's AI, you can generate high-quality articles in seconds. Depending on the length and complexity, most articles can be created within 30 seconds to 2 minutes, dramatically reducing the time compared to traditional writing methods."
    },
    {
      question: "How can I boost my traffic with Copymatic?",
      answer: "Copymatic helps boost traffic through SEO-optimized content creation, keyword research tools, meta descriptions, compelling headlines, and engaging blog posts that rank higher in search engines and attract more visitors to your website."
    },
    {
      question: "Do you offer an API?",
      answer: "Yes, we offer a comprehensive API that allows developers to integrate Copymatic's AI writing capabilities directly into their applications, websites, or workflows for seamless content generation at scale."
    },
    {
      question: "Do you have a WordPress plugin?",
      answer: "Yes, we offer a WordPress plugin that allows you to generate AI-powered content directly within your WordPress admin panel, making it easy to create and publish high-quality content without leaving your CMS."
    }
  ];

  const toggleFAQ = (index:any) => {
    setOpenFAQ(openFAQ === index ? null : index);
  };

  return (
    <div className="relative py-16 px-4 mt-16">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-8">
            Frequently Asked Questions
          </h2>
        </div>
        <div className="space-y-4 mb-16">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="border border-gray-200 rounded-lg overflow-hidden"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full flex items-center justify-between p-6 text-left text-white hover:text-black hover:bg-gray-50 transition-colors"
              >
                <span className="text-lg font-semibold">
                  {faq.question}
                </span>
                <div className="flex-shrink-0 ml-4">
                  {openFAQ === index ? (
                    <svg
                      className="w-6 h-6 text-blue-600"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M20 12H4"
                      />
                    </svg>
                  ) : (
                    <svg
                      className="w-6 h-6 text-blue-600"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M12 6v6m0 0v6m0-6h6m-6 0H6"
                      />
                    </svg>
                  )}
                </div>
              </button>
              {openFAQ === index && (
                <div className="px-6 pb-6">
                  <p className="text-white leading-relaxed">
                    {faq.answer}
                  </p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
         <LoginModal
        isOpen={showLoginModal}
        onClose={() => setShowLoginModal(false)}
      />
    </div>
  );
};

export default FAQSection;